# Generated by Django 4.0.3 on 2022-03-01 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 3, 1, 10, 7, 26, 601176, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
